create table benutzer (
	email varchar(30) not null, 
	passwort varchar(30),
	vorname varchar(30),
	nachname varchar(30),
	adresse varchar(200),
	primary key (email)
);

create table gruppen (
	gruppenid varchar(30) not null,
	email varchar(30),
	primary key (gruppenid, email),
	foreign key (email) references benutzer (email)
);

create table kategorien (
	kategorieid integer not null generated by default as identity,
	kategoriename varchar(30),
	primary key (kategorieid)
);

create table wraps (
	wrapid integer not null generated by default as identity,
	zutat1 varchar(30),
	zutat2 varchar(30),
	zutat3 varchar(30),
	zutat4 varchar(30),
	primary key (wrapid)
);

create table bestellungen (
	bestellungid integer not null generated by default as identity,
	zutat1 varchar(30),
	zutat2 varchar(30),
	zutat3 varchar(30),
	zutat4 varchar(30),
	primary key (bestellungid)
);

create table zutaten (
	zutatid integer not null generated by default as identity,
	zutatname varchar(30),
	info varchar(30),
	bild varchar(30),
	gewicht integer,
	kalorien varchar(30),
	preis double,
	primary key (zutatid)
);


